apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-web-hello-world
  name: go-web-nodeport
spec:
  ports:
  - name: 8085-31080
    port: 8085
    protocol: TCP
    nodePort: 31080
  selector:
    app: go-web-hello-world
  type: NodePort
status:
  loadBalancer: {}
