apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-web-hello-world
  name: go-web-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-web-hello-world
    spec:
      containers:
      - image: sma88/go-web-hello-world:v0.1
        name: go-web-hello-world
        resources: {}
status: {}
